name: Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: Package.Identifier
          installers-regex: '\.msi$' # Only .exe files
          token: ${{ secrets.WINGET_TOKEN }}
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure
      
    - name: compile
      run: make
