name: Build and Release

on:
  workflow_dispatch:
    
jobs:
  winget_submit:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: Package.Identifier
          installers-regex: '\.msi$' # Only .exe files
          token: ${{ secrets.WINGET_TOKEN }}
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure
      
    - name: compile
      run: make
